using System;

namespace ACLS.Sim
{
    // L1-L4 tiered world context generated by LLM during new-game setup.
    // Stored on World so it survives scene changes and feeds into prompts.
    //
    // Cache metaphor (from AIGame design):
    //   L4_World  = macro era / factions / history anchors  (cold, rarely changes)
    //   L3_Expanse = regional powers / tensions              (warm, monthly)
    //   L2_Arena  = near network / active pressures          (hot, every 3-7 days)
    //   L1_Stage  = current scene / active NPCs / exits      (volatile, per scene)
    [Serializable]
    public sealed class WorldStageData
    {
        public string WorldDescription = "";  // player's world choice (preset blurb or custom text)
        public string WorldBuild = "";       // World: era, narrative style, cognitive boundaries, anchors (step 1 output)
        public string L4World   = "";         // macro: era, factions, history anchors
        public string L3Expanse = "";         // regional: power distribution, indirect intel
        public string L2Arena   = "";         // near: 3-14 day contacts, active pressures, opportunities
        public string L1Stage   = "";         // immediate: current scene state (refreshed each scene)

        public bool IsWorldBuilt => !string.IsNullOrWhiteSpace(L4World);
        public bool IsStageBuilt => !string.IsNullOrWhiteSpace(L1Stage);
    }
}
